# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rGetGaussiansFromSpectrum <- function(intensity, mz, params, mzLow, mzHigh) {
    .Call('_iCone_rGetGaussiansFromSpectrum', PACKAGE = 'iCone', intensity, mz, params, mzLow, mzHigh)
}

#' Generic method for the imzMLreader
#' @name imzMLBinReadGeneric
#' @param ibdFname: full path to the ibd file.
#' @param NPixels: Total number of pixels in the image.
#' @param N: number of elemetns (or data point to read).
#' @param offset: offset in bytes at which the reading operation is started.
#' @param read_mz: if true m/z data is readed, otherwise intensities are readed.
#' @param continuous: true if imzML data is in continuous mode
NULL

#' @title Generic method for the imzMLreader
#' @name imzMLBinReadAllMz
#' @param ibdFname: full path to the ibd file.
#' @param NPixels: Total number of pixels in the image.
#' @param N: number of elemetns (or data point to read).
#' @param offset: offset in bytes at which the reading operation is started.
#' @param read_mz: if true m/z data is readed, otherwise intensities are readed.
#' @param continuous: true if imzML data is in continuous mode
imzMLBinReadAllMz <- function(ibdFname, imzML) {
    .Call('_iCone_imzMLBinReadAllMz', PACKAGE = 'iCone', ibdFname, imzML)
}

#' Testing the imzMLwriter in sequential mode
#' This function creates a new ibd file with the provided data descibed in the following params
#' @name testingimzMLBinWriteSequential
#' @param ibdFname: full path to the ibd file.
#' @param mz_dataTypeString: String to specify the data format used to encode m/z values.
#' @param int_dataTypeString: String to specify the data format used to encode intensity values.
#' @param uuid: 16 bytes long UUID.
#' @param mzArray: A matrix with the m/z values for all pixels. Each pixel corresponds to a row. If there is only one row data will be saved in continuous mode
#' @param intArray: A matrix with the intensity values for all pixels. Each pixel corresponds to a row so the number of pixels is extracted from here.
.debug_imzMLBinWriterSequential <- function(ibdFname, mz_dataTypeString, int_dataTypeString, str_uuid, mzArray, intArray) {
    .Call('_iCone_testingimzMLBinWriteSequential', PACKAGE = 'iCone', ibdFname, mz_dataTypeString, int_dataTypeString, str_uuid, mzArray, intArray)
}

#' This function creates a new ibd file with the provided uuid
#' @name CimzMLBinCreateNewIBD
#' @param ibdFname: full path to the ibd file.
#' @param uuid: 16 bytes long UUID.
CimzMLBinCreateNewIBD <- function(ibdFname, str_uuid) {
    invisible(.Call('_iCone_CimzMLBinCreateNewIBD', PACKAGE = 'iCone', ibdFname, str_uuid))
}

#' This function appends a new mass axis to a given ibd file.
#' The last added offset is returned.
#' @name CimzMLBinAppendMass.
#' @param ibdFname: full path to the ibd file.
#' @param mz_dataTypeString:  String to specify the data format used to encode m/z values.
#' @param mzNew: The mass axis to append.
CimzMLBinAppendMass <- function(ibdFname, mz_dataTypeString, mzNew) {
    .Call('_iCone_CimzMLBinAppendMass', PACKAGE = 'iCone', ibdFname, mz_dataTypeString, mzNew)
}

#' @name CimzMLBinAppendIntensity.
#' @title This function appends a new mass axis to a given ibd file.
#'        The last added offset is returned.
#' @param ibdFname: full path to the ibd file.
#' @param int_dataTypeString:  String to specify the data format used to encode m/z values.
#' @param intNew: The mass axis to append.
CimzMLBinAppendIntensity <- function(ibdFname, int_dataTypeString, intNew) {
    .Call('_iCone_CimzMLBinAppendIntensity', PACKAGE = 'iCone', ibdFname, int_dataTypeString, intNew)
}

#' @name CimzMLBinWriteModifyMass
#' @title A method to use the imzMLwriter in modify mode to allow direct modification of mass axes for the calibration
#'        This function modifies data of an ibd file with the following params
#' @param ibdFname: full path to the ibd file.
#' @param NPixels: Total number of pixels in the image.
#' @param mz_dataTypeString: String to specify the data format used to encode m/z values.
#' @param int_dataTypeString: String to specify the data format used to encode intensity values.
#' @param continuous: true if imzML data is in continuous mode
#' @param mzNew: A vector with the m/z values. Must be the same length as the original imzML mass target massa axis.
#' @param mzOffset: offset in the ibd file of the target mass axis.
CimzMLBinWriteModifyMass <- function(ibdFname, NPixels, mz_dataTypeString, int_dataTypeString, continuous, mzNew, mzOffset) {
    invisible(.Call('_iCone_CimzMLBinWriteModifyMass', PACKAGE = 'iCone', ibdFname, NPixels, mz_dataTypeString, int_dataTypeString, continuous, mzNew, mzOffset))
}

#' @name CimzMLBinReadMass.
#' @title Reads a single mass axis from the imzML file.
#' @param ibdFname: full path to the ibd file.
#' @param NPixels: Total number of pixels in the image.
#' @param N: number of elemetns (or data point to read).
#' @param offset: offset in bytes at which the reading operation is started.
#' @param continuous: true if imzML data is in continuous mode
CimzMLBinReadMass <- function(ibdFname, NPixels, N, offset, dataTypeString, continuous) {
    .Call('_iCone_CimzMLBinReadMass', PACKAGE = 'iCone', ibdFname, NPixels, N, offset, dataTypeString, continuous)
}

#' @name CimzMLBinReadIntensity.
#' @title Reads a single mass axis from the imzML file.
#' @param ibdFname: full path to the ibd file.
#' @param NPixels: Total number of pixels in the image.
#' @param N: number of elemetns (or data point to read).
#' @param offset: offset in bytes at which the reading operation is started.
#' @param continuous: true if imzML data is in continuous mode
CimzMLBinReadIntensity <- function(ibdFname, NPixels, N, offset, dataTypeString, continuous) {
    .Call('_iCone_CimzMLBinReadIntensity', PACKAGE = 'iCone', ibdFname, NPixels, N, offset, dataTypeString, continuous)
}

#' @title Method to read a peak list from an imzML file. Processed mode is assumed.
#' @name CimzMLReadPeakList
#' @param ibdFname: full path to the ibd file.
#' @param imzML_peakList_descriptor: imzML file description as it is returned by the CimzMLParse() function.
#' @param PixelID: the pixel ID to read a peak list.
CimzMLReadPeakList <- function(ibdFname, imzML_peakList_descriptor, PixelID) {
    .Call('_iCone_CimzMLReadPeakList', PACKAGE = 'iCone', ibdFname, imzML_peakList_descriptor, PixelID)
}

#' @title Method to overwrite the UUID of an imzML ibd file.
#' @name overwriteIbdUUid
#' @param ibdFname: full path to the ibd file.
#' @param newUUID: the new uuid as a string.
overwriteIbdUUid <- function(ibdFname, newUUID) {
    invisible(.Call('_iCone_overwriteIbdUUid', PACKAGE = 'iCone', ibdFname, newUUID))
}

#' @name Cload_imzMLSpectra
#' @title Load spectra into a Matrix object interpolating to the common mass axis when necessary.
#' @param rMSIobj: an rMSI object prefilled with a parsed imzML.
#' @param pixelIDs: pixel ID's of the spectra to load in C-style indexing (starting at 0).
#' @param commonMassAxis: a common mass axis that may be different than the mass axis in the rMSI object.
#' @param number_of_threads: number of thread to use during interpolation
#'
Cload_imzMLSpectra <- function(rMSIobj, pixelIDs, commonMassAxis, number_of_threads) {
    .Call('_iCone_Cload_imzMLSpectra', PACKAGE = 'iCone', rMSIobj, pixelIDs, commonMassAxis, number_of_threads)
}

#' @name Cload_imzMLImages
#' @title Load images
#' @param rMSIobj: an rMSI object prefilled with a parsed imzML.
#' @param pixelIDs: pixel ID's of the spectra to load in C-style indexing (starting at 0).
#' @param maxIndex: mass index range to load
#' @param commonMassAxis: a common mass axis that may be different than the mass axis in the rMSI object.
#' @param number_of_threads: number of thread to use during interpolation
#' @return a matrix
#' 
Cload_imzMLImages <- function(rMSIobj, pixelIDs, massIndex, commonMassAxis, number_of_threads) {
    .Call('_iCone_Cload_imzMLImages', PACKAGE = 'iCone', rMSIobj, pixelIDs, massIndex, commonMassAxis, number_of_threads)
}

#' @name CimzMLParse
#' @title  imzML resulting data structure:
#' @param xml_path: full path to imzML file
#' @return 
#' UUID: a String object with the UUID
#' continuous_mode: a boolean which is true if spectra in continuous mode
#' compression_mz: a boolean indicating wheher data is compressed or not
#' compression_int: a boolean indicating wheher data is compressed or not
#' mz_dataType: a String with the data type: "float", "int"... etc...
#' int_dataType: a String with the data type: "float", "int"... etc...
#' pixel_size_um: a double with the pixel area? check this...
#' run_data: a data.frane with the columns: x, y, mzLength, mzOffset, intLength, intOffset
#'
CimzMLParse <- function(xml_path) {
    .Call('_iCone_CimzMLParse', PACKAGE = 'iCone', xml_path)
}

CimzMLStore <- function(fname, imgInfo, mass_spectrometer_file_format = "rMSI exported imzML") {
    .Call('_iCone_CimzMLStore', PACKAGE = 'iCone', fname, imgInfo, mass_spectrometer_file_format)
}

rGetPixelGaussians <- function(ibdFname, imzML, params, mzLow, mzHigh, pixel) {
    .Call('_iCone_rGetPixelGaussians', PACKAGE = 'iCone', ibdFname, imzML, params, mzLow, mzHigh, pixel)
}

#'
NULL

#' @name rGetCoordinatesFromFile()
#' @title returns a matrix with the coordinates of all pixels (X/Y).
#' If there are multiple samples, they appear sequentially; that is, the matrix has as many rows 
#' as the cumulative number of pixels in each sample and two columns.
#' @param file   -> file name with pixels coordinates (_pixelsCoord.bin)
#' @param sample -> just download the pixels from this sample.
#'                 if sample < 1, all sample coordinates are returned
#' @return a matrix with the coordinates (X/Y) of pixels.
#' 
rGetPixelsCoordinates <- function(fileName, sample) {
    .Call('_iCone_rGetPixelsCoordinates', PACKAGE = 'iCone', fileName, sample)
}

rGetBasic <- function(file) {
    .Call('_iCone_rGetBasic', PACKAGE = 'iCone', file)
}

rGetCentroid <- function(file, mass, sample) {
    .Call('_iCone_rGetCentroid', PACKAGE = 'iCone', file, mass, sample)
}

peakMatrixR <- function(baseDir, params, mzLow, mzHigh, nPixels, nSamples) {
    .Call('_iCone_peakMatrixR', PACKAGE = 'iCone', baseDir, params, mzLow, mzHigh, nPixels, nSamples)
}

#'
NULL

rawToGaussiansR <- function(baseDir, ibdFname, imzML, params, mzLow, mzHigh, pxList, nThreads) {
    .Call('_iCone_rawToGaussiansR', PACKAGE = 'iCone', baseDir, ibdFname, imzML, params, mzLow, mzHigh, pxList, nThreads)
}

rGetRawBasic <- function(ibdFname, imzML, pxList) {
    .Call('_iCone_rGetRawBasic', PACKAGE = 'iCone', ibdFname, imzML, pxList)
}

rGetAverageGaussianSpectrum <- function(ibdFname, imzML, params, mzLow, mzHigh, pxList, overSampling, nThreads) {
    .Call('_iCone_rGetAverageGaussianSpectrum', PACKAGE = 'iCone', ibdFname, imzML, params, mzLow, mzHigh, pxList, overSampling, nThreads)
}

rGetAverageSpectrum <- function(ibdFname, imzML, params, mzLow, mzHigh, pxList, overSampling) {
    .Call('_iCone_rGetAverageSpectrum', PACKAGE = 'iCone', ibdFname, imzML, params, mzLow, mzHigh, pxList, overSampling)
}

rSaveMassRange <- function(fileName, mzLow, mzHigh, pixelSize) {
    .Call('_iCone_rSaveMassRange', PACKAGE = 'iCone', fileName, mzLow, mzHigh, pixelSize)
}

rLoadMassRange <- function(fileName) {
    .Call('_iCone_rLoadMassRange', PACKAGE = 'iCone', fileName)
}

rGetDirectory <- function(path) {
    .Call('_iCone_rGetDirectory', PACKAGE = 'iCone', path)
}

